### ISSUE TITLE
Bad logrus import

### ISSUE THREAD

**Issue by AlekSi** [blefort/DTDParser#1]
It should be imported as `"github.com/sirupsen/logrus"` (lowercase "sirupsen").

**Comment by blefort** [comment]
Hum... Not sure. My system is case sensitive and the path is `github.com/Sirupsen/logrus`.

When I go install it, it was like this.

The specs [ImportPath](https://golang.org/ref/spec#ImportPath) does not explicitly forces the use of lowercase.

**Comment by AlekSi** [comment]
https://github.com/sirupsen/logrus/blob/master/README.md mentions that on the second line.

```
$ env GO111MODULE=on go get -v github.com/blefort/DTDParser
go: finding github.com/blefort/DTDParser latest
go: downloading github.com/blefort/DTDParser v0.0.0-20190317153012-1be00412d3a4
go: extracting github.com/blefort/DTDParser v0.0.0-20190317153012-1be00412d3a4
go: finding github.com/Sirupsen/logrus v1.4.2
go: downloading github.com/Sirupsen/logrus v1.4.2
go: extracting github.com/Sirupsen/logrus v1.4.2
go: github.com/blefort/DTDParser imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```

**Comment by scrib-dev** [comment]
Ok, I will try to reinstall and see how it goes

**Comment by blefort** [comment]
Ok, I will try to reinstall and see how it goes

**Comment by blefort** [comment]
Which OS are you using? The CI tool can use it.
